services:
  chat.db:
    image: mysql:8.0.29
    container_name: mysql
    environment:
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_TCP_PORT: 3306
    restart: always
    volumes:
      - chat_mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'

volumes:
  chat_mysql_data:
    name: chat_mysql_data
